import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header className="p-6 bg-gray-700 text-slate-300 border-b-2 flex justify-between">
          <div>LOGO</div>
          <ul className="flex justify-between gap-3 items-center">
            <li>
              <Link href="/featuredProducts">Produtos</Link>
            </li>
            <li>
              <Link href={`/productDetails/${1000}`}>Detalhes</Link>
            </li>
          </ul>
        </header>
        <hr />
        {children}
      </body>
    </html>
  );
}
